### ISSUE TITLE
Suggest .htaccess rules to prevent some erroneous cache directories

### ISSUE THREAD

**Issue by raamdev** [websharks/comet-cache#101]
During my testing of the new branched cache structure on a live site, I found that after several days my cache had the following directories:

```
69-16-219-214/
ftp-raamdev-com/
raamdev-com/
RAAMDEV-COM/
raamdev-comhttp/
```

Some of these should not exist, notably the uppercase `RAAMDEV-COM` and `raamdev-comhttp`.

**Comment by sallyfarmer** [comment]
Ever since I installed zen cache at http://alcohol-abuse-and-addictions-agency.co.uk unless an .htaccess is not present at file manager the whole site is down. Even with the .htaccess deleted and the site is up none of the page or posts links work. permalinks is set to %postnames% at the bottom of the list. The .htaccess regularly re-appears and when it does the site comes down. I cannot just delete zencache as now i don't want to be further messed up. I have aws account with a created distribution correctly setup as per your excellent video with a cname at cpanel cdn. etc. i USED THE 

# BEGIN Host Enforcer

<IfModule rewrite_module>
    RewriteEngine on
    RewriteBase /

```
RewriteCond %{HTTP_HOST} !^example\.com$
RewriteCond %{HTTPS} !^on$ [NC]
RewriteCond %{HTTP:X-Forwarded-Proto} !^https$ [NC]
RewriteRule .* http://example.com%{REQUEST_URI} [R=301,L]

RewriteCond %{HTTP_HOST} !^example\.com$
RewriteCond %{HTTPS} ^on$ [NC,OR]
RewriteCond %{HTTP:X-Forwarded-Proto} ^https$ [NC]
RewriteRule .* https://example.com%{REQUEST_URI} [R=301,L]
```

</IfModule>

# END Host Enforcer

by replacing example with alcohol-abuse-and-addictions-agency.co.uk within it being careful that it was exactly the same bar the href but it didn't work and the only way i could get the site to show again was by deleting the .htaccess file agin completely. Still no links work but the cloudfront aws is very fast in rendering  links that don't work

**Comment by raamdev** [comment]
@sallyfarmer It sounds like you may have an error in your `.htaccess` file, or a misconfiguration on your web server. I recommend contacting your web hosting company and asking them why the `.htaccess` file isn't working, as they have access to the server logs and they can diagnose this issue.

**Comment by jaswrks** [comment]
@raamdev I'm just noting that this is another candidate for our new `.htaccess` tweaks system.

**Comment by renzms** [comment]
Tested for Site using NGINX


![screen shot 2017-02-03 at 8 05 56 pm](https://cloud.githubusercontent.com/assets/13220018/22590934/de06f7ea-ea4c-11e6-9bcb-1afcfeba8516.png)

Also tried adding the following manually for sites that use NGINX:

```
# Enforce exact host name.
<IfModule rewrite_module>
    RewriteEngine on
    RewriteBase /

    RewriteCond %{HTTP_HOST} !^domain.net$
    RewriteCond %{HTTPS} !^on$ [NC]
    RewriteCond %{HTTP:X-Forwarded-Proto} !^https$ [NC]
    RewriteRule .* http://domain.net%{REQUEST_URI} [R=301,L]

    RewriteCond %{HTTP_HOST} !^domain.net$
    RewriteCond %{HTTPS} ^on$ [NC,OR]
    RewriteCond %{HTTP:X-Forwarded-Proto} ^https$ [NC]
    RewriteRule .* https://domain.net%{REQUEST_URI} [R=301,L]
</IfModule>
```


was unable to continue testing as there were problems with server detection please see comment [here](https://github.com/websharks/comet-cache/issues/748#issuecomment-277236883)

**Comment by renzms** [comment]
@raamdev 

### Confirmed Working



Tested Using:


WordPress Version: 4.7.2
Current WordPress Theme: Twenty Seventeen version 1.1
Theme Author: the WordPress team - https://wordpress.org/
Theme URI: https://wordpress.org/themes/twentyseventeen/
Active Plugins: Comet Cache Pro Version 170209-RC
PHP Version: 7.0.10
MySQL Version: 10.0.29-MariaDB-0ubuntu0.16.04.1
Apache Version: Apache/2.4.10 (Debian)

Tested using different incorrect web addresses/ made up subdomains; such as `http://foo.bar.php70-renz.wpsharks.net/path`, the IP itself, and `ftp.php70-renz.wpsharks.net`.




![screen shot 2017-02-13 at 5 25 41 pm](https://cloud.githubusercontent.com/assets/13220018/22877744/c9c6859e-f211-11e6-88c3-0fce4462eb84.png)


**No erroneous cache directories:**

![screen shot 2017-02-13 at 5 27 44 pm](https://cloud.githubusercontent.com/assets/13220018/22877743/c9c3a6a8-f211-11e6-80bb-d43fafceb09d.png)

**Comment by raamdev** [comment]
**Comet Cache v170220** has been released and includes changes from this GitHub Issue. See the [v170220 announcement](https://cometcache.com/blog/comet-cache-v170220-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#101).
